apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: naix-ru-tls
spec:
  secretName: naix-ru
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: naix.ru
  dnsNames:
    - naix.ru
    - www.naix.ru
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - naix.ru
          - www.naix.ru